---
- name: Playbook to configure a podman server
  hosts: all
  remote_user: root

  tasks:
  - name: Set hostname
    hostname:
      name: pod1

  - name: Install podman
    package:
      name: podman
      state: present

  - name: Setup a podman collector
    containers.podman.podman_container:
      name: otel-col
      image: docker.io/otel/opentelemetry-collector:latest
      expose:
        - 4318
      volume:
        - ~/config.yaml:/etc/otelcol/config.yaml
