# Generated by Anaconda 40.22.3.33
# Generated by pykickstart v3.52.9
#version=RHEL10
# Use graphical install
graphical --non-interactive

%addon com_redhat_kdump --enable --reserve-mb='auto'

%end

# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us'
# System language
lang en_US.UTF-8

# Network information
network  --bootproto=dhcp --device=ens18 --nameserver=9.9.9.9,1.1.1.1 --ipv6=auto --hostname tmpl.cmk.lan --activate

%packages
@^server-product-environment
@guest-agents

%end

# Do not Run the Setup Agent on first boot
firstboot --disable

# Generated using Blivet version 3.10.0
ignoredisk --only-use=sda
# System bootloader configuration
bootloader --append="crashkernel=2G-64G:256M,64G-:512M" --location=mbr --boot-drive=sda
autopart
# Partition clearing information
clearpart --none --initlabel

# System timezone
timezone America/New_York --utc

# Root password
rootpw --plaintext --allow-ssh cmkadmin123

## Non-interactive options
eula --agreed

reboot --eject
